// Fixture data matching NCERT/Class_7/Science/ PDF filenames exactly.
// Used by plan catalog, plan regenerate, and lesson tests.

export const CLASS7_SCIENCE_CHAPTERS = [
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 1,
    chapterName: 'The Ever-Evolving World of Science',
    difficulty: 'easy',
    estimatedMinutes: 60,
    concepts: ['Scientific method', 'Observation', 'Hypothesis', 'Experiment'],
    keyFacts: ['Science is based on systematic observation', 'Hypothesis must be testable'],
    textbookQuestions: [
      { question: 'What is the scientific method?', answer: 'A systematic process of observation, hypothesis, and experimentation.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 2,
    chapterName: 'Exploring Substances: Acidic, Basic and Neutral',
    difficulty: 'medium',
    estimatedMinutes: 75,
    concepts: ['Acids', 'Bases', 'Neutralisation', 'pH scale', 'Indicators'],
    keyFacts: ['Acids turn blue litmus red', 'Bases turn red litmus blue', 'pH < 7 is acidic'],
    textbookQuestions: [
      { question: 'What happens when an acid and base are mixed?', answer: 'They neutralise each other to form salt and water.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 3,
    chapterName: 'Electricity: Circuits and Their Components',
    difficulty: 'medium',
    estimatedMinutes: 90,
    concepts: ['Electric circuit', 'Conductors', 'Insulators', 'Series circuit', 'Parallel circuit'],
    keyFacts: ['Current flows from positive to negative terminal', 'Metals are good conductors'],
    textbookQuestions: [
      { question: 'What is an electric circuit?', answer: 'A closed path through which electric current flows.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 4,
    chapterName: 'The World of Metals and Non-Metals',
    difficulty: 'easy',
    estimatedMinutes: 60,
    concepts: ['Properties of metals', 'Properties of non-metals', 'Reactivity series'],
    keyFacts: ['Metals are malleable and ductile', 'Non-metals are brittle'],
    textbookQuestions: [
      { question: 'Name two properties of metals.', answer: 'Metals are malleable and good conductors of electricity.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 5,
    chapterName: 'Changes Around Us: Physical and Chemical',
    difficulty: 'easy',
    estimatedMinutes: 60,
    concepts: ['Physical change', 'Chemical change', 'Reversible change', 'Irreversible change'],
    keyFacts: ['Burning is a chemical change', 'Melting ice is a physical change'],
    textbookQuestions: [
      { question: 'Give one example of a chemical change.', answer: 'Burning of wood produces ash and smoke, which cannot be reversed.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 6,
    chapterName: 'Adolescence: A Stage of Growth and Change',
    difficulty: 'easy',
    estimatedMinutes: 75,
    concepts: ['Puberty', 'Hormones', 'Secondary sexual characters', 'Reproductive health'],
    keyFacts: ['Adolescence starts around age 10–12', 'Hormones control puberty changes'],
    textbookQuestions: [
      { question: 'What is puberty?', answer: 'The stage of life when the body becomes capable of reproduction.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 7,
    chapterName: 'Heat Transfer in Nature',
    difficulty: 'medium',
    estimatedMinutes: 90,
    concepts: ['Conduction', 'Convection', 'Radiation', 'Thermal equilibrium'],
    keyFacts: ['Heat flows from hot to cold body', 'Radiation does not need a medium'],
    textbookQuestions: [
      { question: 'What is conduction?', answer: 'Transfer of heat through a solid material without movement of the material itself.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 8,
    chapterName: 'Measurement of Time and Motion',
    difficulty: 'easy',
    estimatedMinutes: 60,
    concepts: ['Speed', 'Distance', 'Time', 'Uniform motion', 'Non-uniform motion'],
    keyFacts: ['Speed = Distance / Time', 'SI unit of speed is m/s'],
    textbookQuestions: [
      { question: 'What is the formula for speed?', answer: 'Speed equals distance divided by time.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 9,
    chapterName: 'Life Processes in Animals',
    difficulty: 'medium',
    estimatedMinutes: 90,
    concepts: ['Nutrition', 'Respiration', 'Transportation', 'Excretion'],
    keyFacts: ['Digestion starts in the mouth', 'Lungs exchange oxygen and carbon dioxide'],
    textbookQuestions: [
      { question: 'What is the role of the stomach in digestion?', answer: 'The stomach churns food and mixes it with digestive juices to break down proteins.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 10,
    chapterName: 'Life Processes in Plants',
    difficulty: 'medium',
    estimatedMinutes: 90,
    concepts: ['Photosynthesis', 'Transpiration', 'Respiration in plants', 'Transport in plants'],
    keyFacts: ['Chlorophyll absorbs sunlight', 'Stomata control gas exchange in leaves'],
    textbookQuestions: [
      { question: 'What is photosynthesis?', answer: 'The process by which plants use sunlight, water and carbon dioxide to produce glucose and oxygen.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 11,
    chapterName: 'Light: Shadows and Reflections',
    difficulty: 'medium',
    estimatedMinutes: 75,
    concepts: ['Rectilinear propagation of light', 'Shadow formation', 'Reflection', 'Laws of reflection'],
    keyFacts: ['Light travels in a straight line', 'Angle of incidence equals angle of reflection'],
    textbookQuestions: [
      { question: 'State the law of reflection.', answer: 'The angle of incidence is equal to the angle of reflection, and both lie in the same plane.' },
    ],
    pdfS3Key: null,
  },
  {
    class: 7,
    board: 'CBSE',
    subject: 'Science',
    chapterNumber: 12,
    chapterName: 'Earth, Moon and the Sun',
    difficulty: 'hard',
    estimatedMinutes: 120,
    concepts: ['Revolution', 'Rotation', 'Phases of moon', 'Solar and lunar eclipse', 'Tides'],
    keyFacts: ['Earth takes 365.25 days to revolve around the Sun', 'Moon takes ~29.5 days to complete one lunar cycle'],
    textbookQuestions: [
      { question: 'Why do we see different phases of the moon?', answer: 'Because different portions of the moon\'s illuminated half are visible from Earth as it revolves around Earth.' },
    ],
    pdfS3Key: null,
  },
];

// Lightweight version returned by GET /api/plan/chapters
export const CLASS7_SCIENCE_CHAPTER_LIST = CLASS7_SCIENCE_CHAPTERS.map((ch) => ({
  chapterNumber: ch.chapterNumber,
  chapterName: ch.chapterName,
  estimatedMinutes: ch.estimatedMinutes,
  difficulty: ch.difficulty,
}));

// Subset used by plan regenerate and lesson tests
export const SELECTED_CHAPTER_INDICES = [0, 2, 6]; // ch_01, ch_03, ch_07
